# Generated by Django 5.0.6 on 2024-10-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('DD', 'Adidas'), ('BA', 'Bata'), ('CO', 'Converse'), ('FI', 'Fila'), ('NB', 'New Balance'), ('NI', 'Nike'), ('PU', 'Puma'), ('RB', 'Reebok'), ('TL', 'Timberland'), ('VA', 'Vans')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
