# Generated by Django 5.0.6 on 2024-11-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_productnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productnew',
            options={'ordering': ('-id',), 'verbose_name': 'New Products', 'verbose_name_plural': 'New Products'},
        ),
    ]
