# Generated by Django 5.0.6 on 2024-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_productnew_discounted_price_productnew_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='productnew',
            options={'ordering': ('-discounted_price',), 'verbose_name': 'New Products', 'verbose_name_plural': 'New Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], default='*', max_length=5),
        ),
    ]
