# Generated by Django 5.0.6 on 2024-11-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_product_options_alter_productnew_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
