# Generated by Django 5.2.5 on 2025-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-id',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(default=1),
        ),
    ]
